# Generated by Django 3.2.18 on 2023-03-23 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=255)),
                ('not_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('number_of_votes', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('longevity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('sillage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('designers', models.ManyToManyField(to='base.Designer')),
                ('notes', models.ManyToManyField(to='base.Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
