# Generated by Django 3.2.18 on 2023-03-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230323_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='not_type',
            new_name='note_type',
        ),
    ]
