# Generated by Django 3.2.18 on 2023-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_not_type_note_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='longevity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='sillage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
