# Generated by Django 3.2.18 on 2023-03-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230323_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='designers',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Designer',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
