# Generated by Django 3.2.18 on 2023-03-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230324_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes',
            field=models.ManyToManyField(to='base.Note'),
        ),
    ]
