# Generated by Django 3.2.18 on 2023-03-28 08:41

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230327_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(null=True, upload_to=base.models.perfume_image_file_path),
        ),
    ]
